### PR TITLE
cmd/ll2go: Add prel. support for alloca.

### PR DESCRIPTION
**Pull request by sangisos**
Updates #187

### CODE REVIEW

**Comment by mewmew** [comment]
Thanks!! This was the last unimplemented instructions.

**Comment by mewmew** [comment]
@sangisos Just for public records, would you be willing to release your contribution into the [public domain](https://github.com/decomp/decomp#public-domain)? The intention is to keep the project source code in the public domain to simplify license handling for the end user.

**Comment by sangisos** [comment]
This is my release of all my code in this project in the CC0 public domain licence.

**Comment by mewmew** [comment]
> This is my release of all my code in this project in the CC0 public domain licence.

Music to my open source heart <3

**Pull request merged**
